AllCops:
  DisplayCopNames: true
  Exclude:
    - 'tmp/**/**'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/StringConversionInInterpolation:
  Exclude:
    # Refinements が文字列埋め込みで効かない
    - 'lib/pretty_validation/validation.rb'

Metrics/AbcSize:
  Max: 20

Lint/HandleExceptions:
  Enabled: false
